const cardCarouselData = [
  {
    id: 1,
    title: "Cozy Apartment",
    subtitle: "2 BHK in downtown",
    image: "https://picsum.photos/id/1018/600/400",
    description: "Bright apartment with city views and modern kitchen.",
  },
  {
    id: 2,
    title: "Modern Loft",
    subtitle: "Open plan living",
    image: "https://picsum.photos/id/1025/600/400",
    description: "Loft with high ceilings and lots of natural light.",
  },
  {
    id: 3,
    title: "Penthouse Suite",
    subtitle: "Skyline view",
    image: "https://picsum.photos/id/1031/600/400",
    description: "Luxurious top-floor suite with private terrace.",
  },
  {
    id: 4,
    title: "Garden House",
    subtitle: "Private backyard",
    image: "https://picsum.photos/id/1043/600/400",
    description: "Charming house with a large private garden.",
  },
  {
    id: 5,
    title: "Studio Flat",
    subtitle: "Compact & smart",
    image: "https://picsum.photos/id/1050/600/400",
    description: "Perfect starter studio with efficient layout.",
  },
  {
    id: 6,
    title: "Beach Villa",
    subtitle: "Steps from the sand",
    image: "https://picsum.photos/id/1062/600/400",
    description: "Wake up to ocean views in this spacious villa.",
  },
  {
    id: 7,
    title: "Country Cottage",
    subtitle: "Peaceful retreat",
    image: "https://picsum.photos/id/1074/600/400",
    description: "Cozy cottage surrounded by rolling hills.",
  },
  {
    id: 8,
    title: "City Condo",
    subtitle: "Convenient location",
    image: "https://picsum.photos/id/1084/600/400",
    description: "Condo close to transport, shops and cafes.",
  },
  {
    id: 9,
    title: "Suburban Home",
    subtitle: "Family-friendly",
    image: "https://picsum.photos/id/109/600/400",
    description: "Four-bedroom home in a quiet neighborhood.",
  },
  {
    id: 10,
    title: "Riverside Cabin",
    subtitle: "Nature escape",
    image: "https://picsum.photos/id/110/600/400",
    description: "Rustic cabin on the river, great for weekends.",
  },
  {
    id: 11,
    title: "Designer Flat",
    subtitle: "High-end finishes",
    image: "https://picsum.photos/id/111/600/400",
    description: "Designer interiors with premium fixtures.",
  },
  {
    id: 12,
    title: "Mountain Chalet",
    subtitle: "Ski access",
    image: "https://picsum.photos/id/112/600/400",
    description: "Chalet with ski-in ski-out convenience.",
  },
];

export default cardCarouselData;
